---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Docker dependencies
  ansible.builtin.apt:
    name:
      - 'apt-transport-https'
      - 'ca-certificates'
      - 'curl'
      - 'software-properties-common'

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name: docker-ce
    state: present

# - name: Pull Docker image
#   ansible.builtin.shell: docker build -t {{ docker_image_name }} /home/adminuser
#   args:
#     creates: /path/to/created_file  # Specify a file that indicates whether the task is needed

# - name: Run Docker container
#   ansible.builtin.shell: docker run -d -p 8080:8080 {{ docker_image_name }}
#   args:
#     creates: /path/to/created_file  # Specify a file that indicates whether the task is needed
