---
- name: Install required system packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - 'apt-transport-https'
    - 'ca-certificates'
    - 'curl'
    - 'software-properties-common'
    - 'python3-pip'
    - 'virtualenv'
    - 'python3-setuptools'
  tags: install_system_packages

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: add_docker_gpg_key

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  tags: add_docker_repository

- name: Update apt and install docker-ce
  ansible.builtin.apt:
    update_cache: true
    name: docker-ce
    state: present
  tags: install_docker_ce

- name: Install Docker Module for Python
  ansible.builtin.pip:
    name: docker
  tags: install_docker_python_module

- name: Pull Docker image
  community.docker.docker_image:
    name: "{{ deploy_docker_image }}"
    state: present

- name: Run Docker container
  community.docker.docker_container:
    name: "{{ deploy_container }}"
    image: "{{ deploy_docker_image }}"
    state: started
    ports: "{{ deploy_ports }}"
