---
- name: Deploy
  hosts: devopspetclinic.westeurope.cloudapp.azure.com
  connection: ssh
  become: true
  tasks:
    - name: Run deploy
      ansible.builtin.import_role:
        name: deploy
        tasks_from: deploy
