name: Code quality
on:   # yamllint disable-line rule:truthy
  # push:
  #   branches:
  #     - '**'    # matches every branch
  workflow_dispatch:

jobs:
  Run_ADDS_Terraform_validate:
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6
      - name: Run Terraform validate
        working-directory: ./terraform/
        run: |
          terraform init -backend=false
          terraform validate

  Run_TFLint:
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install tflint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.47.0
      - name: Run TFLint
        working-directory: ./terraform/
        run: tflint -f compact --recursive

  Run_Ansible_Lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Ansible lint requirements
        run: pip install ansible==8.2.0 ansible-lint==6.18.0 pywinrm==0.4.3
      - name: Run Ansible lint
        working-directory: ./ansible/
        run: ansible-lint

  Run_Robot_Lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Robot lint
        run: pip install robotframework-robocop==4.1.0
      - name: Run Robot lint
        run: robocop --reports all

  Run_Python_Lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Python lint
        run: pip install ruff==0.0.286
      - name: Run Python lint
        run: ruff check --show-source .