name: Deploy Petclinic webapp
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
  
    - name: Terraform apply
      run: |
        cd ~/actions-runner/_work/devopspetclinic/devopspetclinic/devops/terraform
        terraform init
        terraform apply -auto-approve
        
    - name: Run Terraform output
      working-directory: ./terraform/
      run: terraform output -json

  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Maven package
      working-directory: ./    
      run: |
        mvn package
        cp ./target/petclinic.war ./tomcat/petclinic.war

    - name: Create docker image
      working-directory: ./tomcat
      run: docker build -t alandevoteam/petclinic:latest .
      
    - name: Push Docker image
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push alandevoteam/petclinic:latest

    - name: Kick off Ansible deploy
      working-directory: ./ansible
      run: ansible-playbook deploy.yml -i inventory.yml
