name: Deploy Petclinic webapp
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
      
    - name: Confirm Git identity
      run: |
        git config --global user.email "alan.ahmad@devoteam.com"
        git config --global user.name "alandevoteam"
    
    - name: Maven package
      run: |
        cd ~/actions-runner/_work/devopspetclinic/devopspetclinic
        mvn package

    - name: Terraform apply
      run: |
        cd ~/actions-runner/_work/devopspetclinic/devopspetclinic/devops/terraform
        terraform init
        terraform apply -auto-approve
        
    - name: Run Terraform output
      working-directory: ./adds/terraform/
      run: terraform output -json

# - name: Create Dockerfile
#   ansible.builtin.copy:
#     dest: /home/adminuser/Dockerfile
#     content: |
#       FROM ubuntu:latest 
#       RUN apt-get -y update && apt-get -y upgrade
#       RUN apt-get -y install openjdk-8-jdk wget
#       RUN mkdir /usr/local/tomcat
#       RUN wget https://downloads.apache.org/tomcat/tomcat-9/v9.0.76/bin/apache-tomcat-9.0.76.tar.gz -O /tmp/tomcat.tar.gz
#       RUN cd /tmp && tar xvfz tomcat.tar.gz
#       RUN cp -Rv /tmp/apache-tomcat-9.0.76/* /usr/local/tomcat/
#       ADD tomcat-users.xml /usr/local/tomcat/conf/
#       ADD context.xml /usr/local/tomcat/webapps/manager/META-INF
#       ADD petclinic-{{ warfile }} /usr/local/tomcat/webapps/
#       EXPOSE 8080
#       CMD /usr/local/tomcat/bin/catalina.sh run
#   mode: "0644"

    - name: Update ansible inventory
      run: |
        echo "[testing-vm]" > ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/ansible/inventory.ini
        echo "testpetclinic.westeurope.cloudapp.azure.com ansible_user=adminuser ansible_ssh_pass=P@assword1234. VERSION=${{ steps.extract_version.outputs.version }}" >> ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/ansible/inventory.ini
        echo "" >> ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/ansible/inventory.ini

    - name: Open webapp
      run: ipaddress
