name: Deploy Petclinic webapp
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
      
    - name: Confirm Git identity
      run: |
        git config --global user.email "alan.ahmad@devoteam.com"
        git config --global user.name "alandevoteam"

    - name: Extract version from POM file
      id: extract_version
      run: |
        version=$(grep -oP '(?<=<version>)[^<]+' pom.xml)
        version=$(echo $version | grep -oP '^\d+\.\d+\.\d+')
        echo "::set-output name=version::$version"

    - name: Maven package
      run: |
        cd ~/actions-runner/_work/devopspetclinic/devopspetclinic
        mvn package

    - name: Set up infrastructure in AZURE CLOUD
      run: |
        cd ~/actions-runner/_work/devopspetclinic/devopspetclinic/devops/terraform
        terraform init
        terraform apply -auto-approve
        
    - name: Terraform Infrastructure task completed
      run: sleep 60

    - name: Update release version in ansible inventory
      run: |
        echo "[testing-vm]" > ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/ansible/inventory.ini
        echo "testpetclinic.westeurope.cloudapp.azure.com ansible_user=adminuser ansible_ssh_pass=P@assword1234. VERSION=${{ steps.extract_version.outputs.version }}" >> ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/ansible/inventory.ini
        echo "" >> ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/ansible/inventory.ini
 
    - name: Update Selenium script with version number
      run: sed -i "s|http://xptpetclinic.westeurope.cloudapp.azure.com:8080/petclinic-|http://prodpetclinic.westeurope.cloudapp.azure.com/petclinic-${{ steps.extract_version.outputs.version }}/|g" ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/seleniumscript.py
   
    - name: Update JMeter script with version
      run: sed -i "s|<stringProp name=\"HTTPSampler.path\">/petclinic-/</stringProp>|<stringProp name=\"HTTPSampler.path\">/petclinic-${{ steps.extract_version.outputs.version }}/</stringProp>|" ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/petclinic_loadtest_plan.jmx
      
    - name: environment configuration completed
      run: sleep 10

    - name: Start Jmeter loadtest, fall back if test fails.
      run: /opt/jmeter/bin/jmeter -n -t ~/actions-runner/_work/devopspetclinic/devopspetclinic/src/test/petclinic_loadtest_plan.jmx -l ~/actions-runner/_work/devopspetclinic/devopspetclinic/devops/tests/file.jtl

    - name: Start Selenium script, fall back if test fails.
      run: python3 ~/actions-runner/_work/devopspetclinic/devopspetclinic/devops/tests/seleniumscript.py
  
    - name: Webapp is in production!
      run: sleep 10
