name: Destroy Azure resources
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
  
    - name: Terraform destroy
      run: |
        cd ~/actions-runner/_work/petclinic/petclinic/terraform
        terraform init
        terraform destroy -auto-approve